networks:
  transfer_net:
    driver: bridge

services:
  db:
    image: postgres:18.1
    container_name: postgres_db
    restart: always
    ports:
      - "5022:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${VOLUME_POSTGRES}
    networks:
      - transfer_net
    
  server:
    #build: ./WebApiTransfer/transfer-back
    image: avalentyn/transfer-api:latest
    container_name: transfer_api
    restart: always
    volumes:
      - ${VOLUME_SERVER_API}
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=db;Database=${POSTGRES_DB};Port=5432;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    ports:
      - "5898:8080"
    depends_on:
      - db
    networks:
      - transfer_net

  front:
    build: 
      context: ./my-transfer-ts/transfer-front
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    container_name: react_front
    depends_on:
      - server
    ports:
      - "3987:80"
    networks:
      - transfer_net