services:
  db:
    image: postgres:18.1
    container_name: db
    restart: always
    ports:
      - "5022:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /data/transfer/postgres:/var/lib/postgresql

  server: 
    build: ./WebApiTransfer/transfer-back
    container_name: transfer_api
    volumes:
      - /data/transfer/images:/app/images
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=db;Database=mydb;Port=5022;Username=ivan;Password=marko123halosh
    ports:
      - "5898:8080"
    depends_on:
      - db

  front:
    build: 
      context: ./my-transfer-ts/transfer-front
    container_name: transfer_ts_front
    depends_on:
      - server
    ports:
      - "3987:80"

